
family = "NotoColorEmoji-cff2-colr"
output_file = "NotoColorEmoji-cff2-colr.otf"
color_format = "cff2_colr_1"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = [
  "../font-srcs/noto-emoji/svg/*.svg",
  "../font-srcs/noto-emoji/third_party/region-flags/waved-svg/*",
]

[master.regular.position]
wght = 400
